<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class InsertCitiesAndGovernorates extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        \Illuminate\Support\Facades\DB::table('governorates')->insert([
            ['id' => 1, 'value_AR' => 'القاهرة', 'value_EN' => 'Cairo'],
            ['id' => 2, 'value_AR' => 'الجيزة', 'value_EN' => 'Giza'],
            ['id' => 3, 'value_AR' => 'الأسكندرية', 'value_EN' => 'Alexandria'],
            ['id' => 4, 'value_AR' => 'الدقهلية', 'value_EN' => 'Dakahlia'],
            ['id' => 5, 'value_AR' => 'البحر الأحمر', 'value_EN' => 'Red Sea'],
            ['id' => 6, 'value_AR' => 'البحيرة', 'value_EN' => 'Beheira'],
            ['id' => 7, 'value_AR' => 'الفيوم', 'value_EN' => 'Fayoum'],
            ['id' => 8, 'value_AR' => 'الغربية', 'value_EN' => 'Gharbiya'],
            ['id' => 9, 'value_AR' => 'الإسماعلية', 'value_EN' => 'Ismailia'],
            ['id' => 10, 'value_AR' => 'المنوفية', 'value_EN' => 'Monofia'],
            ['id' => 11, 'value_AR' => 'المنيا', 'value_EN' => 'Minya'],
            ['id' => 12, 'value_AR' => 'القليوبية', 'value_EN' => 'Qaliubiya'],
            ['id' => 13, 'value_AR' => 'الوادي الجديد', 'value_EN' => 'New Valley'],
            ['id' => 14, 'value_AR' => 'السويس', 'value_EN' => 'Suez'],
            ['id' => 15, 'value_AR' => 'اسوان', 'value_EN' => 'Aswan'],
            ['id' => 16, 'value_AR' => 'اسيوط', 'value_EN' => 'Assiut'],
            ['id' => 17, 'value_AR' => 'بني سويف', 'value_EN' => 'Beni Suef'],
            ['id' => 18, 'value_AR' => 'بورسعيد', 'value_EN' => 'Port Said'],
            ['id' => 19, 'value_AR' => 'دمياط', 'value_EN' => 'Damietta'],
            ['id' => 20, 'value_AR' => 'الشرقية', 'value_EN' => 'Sharkia'],
            ['id' => 21, 'value_AR' => 'جنوب سيناء', 'value_EN' => 'South Sinai'],
            ['id' => 22, 'value_AR' => 'كفر الشيخ', 'value_EN' => 'Kafr Al sheikh'],
            ['id' => 23, 'value_AR' => 'مطروح', 'value_EN' => 'Matrouh'],
            ['id' => 24, 'value_AR' => 'الأقصر', 'value_EN' => 'Luxor'],
            ['id' => 25, 'value_AR' => 'قنا', 'value_EN' => 'Qena'],
            ['id' => 26, 'value_AR' => 'شمال سيناء', 'value_EN' => 'North Sinai'],
            ['id' => 27, 'value_AR' => 'سوهاج', 'value_EN' => 'Sohag']
        ]);
        \Illuminate\Support\Facades\DB::table('cities')->insert([
            ['id' =>1  ,'gov_id' => 1, 'value_AR' =>'القاهره', 'value_EN' =>'Cairo'],
            ['id' =>2  ,'gov_id' => 2, 'value_AR' =>'الجيزة', 'value_EN' =>'Giza'],
            ['id' =>3  ,'gov_id' => 2, 'value_AR' =>'السادس من أكتوبر', 'value_EN' =>'Sixth of October'],
            ['id' =>4  ,'gov_id' => 2, 'value_AR' =>'الشيخ زايد', 'value_EN' =>'Cheikh Zayed'],
            ['id' =>5  ,'gov_id' => 2, 'value_AR' =>'الحوامدية', 'value_EN' =>'Hawamdiyah'],
            ['id' =>6  ,'gov_id' => 2, 'value_AR' =>'البدرشين', 'value_EN' =>'Al Badrasheen'],
            ['id' =>7  ,'gov_id' => 2, 'value_AR' =>'الصف', 'value_EN' =>'Saf'],
            ['id' =>8  ,'gov_id' => 2, 'value_AR' =>'أطفيح', 'value_EN' =>'Atfih'],
            ['id' =>9  ,'gov_id' => 2, 'value_AR' =>'العياط', 'value_EN' =>'Al Ayat'],
            ['id' =>10 ,'gov_id' => 2, 'value_AR' =>'الباويطي', 'value_EN' =>'Al-Bawaiti'],
            ['id' =>11 ,'gov_id' => 2, 'value_AR' =>'منشأة القناطر', 'value_EN' =>'ManshiyetAl Qanater'],
            ['id' =>12 ,'gov_id' => 2, 'value_AR' =>'أوسيم', 'value_EN' =>'Oaseem'],
            ['id' =>13 ,'gov_id' => 2, 'value_AR' =>'كرداسة', 'value_EN' =>'Kerdasa'],
            ['id' =>14 ,'gov_id' => 2, 'value_AR' =>'أبو النمرس', 'value_EN' =>'Abu Nomros'],
            ['id' =>15 ,'gov_id' => 2, 'value_AR' =>'كفر غطاطي', 'value_EN' =>'Kafr Ghati'],
            ['id' =>16 ,'gov_id' => 2, 'value_AR' =>'منشأة البكاري', 'value_EN' =>'Manshiyet Al Bakari'],
            ['id' =>17 ,'gov_id' => 3, 'value_AR' =>'الأسكندرية', 'value_EN' =>'Alexandria'],
            ['id' =>18 ,'gov_id' => 3, 'value_AR' =>'برج العرب', 'value_EN' =>'Burj Al Arab'],
            ['id' =>19 ,'gov_id' => 3, 'value_AR' =>'برج العرب الجديدة', 'value_EN' =>'New Burj Al Arab'],
            ['id' =>20 ,'gov_id' => 12,'value_AR' => 'بنها', 'value_EN' =>'Banha'],
            ['id' =>21 ,'gov_id' => 12,'value_AR' => 'قليوب', 'value_EN' =>'Qalyub'],
            ['id' =>22 ,'gov_id' => 12,'value_AR' => 'شبرا الخيمة', 'value_EN' =>'Shubra Al Khaimah'],
            ['id' =>23 ,'gov_id' => 12,'value_AR' => 'القناطر الخيرية', 'value_EN' =>'Al Qanater Charity'],
            ['id' =>24 ,'gov_id' => 12,'value_AR' => 'الخانكة', 'value_EN' =>'Khanka'],
            ['id' =>25 ,'gov_id' => 12,'value_AR' => 'كفر شكر', 'value_EN' =>'Kafr Shukr'],
            ['id' =>26 ,'gov_id' => 12,'value_AR' => 'طوخ', 'value_EN' =>'Tukh'],
            ['id' =>27 ,'gov_id' => 12,'value_AR' => 'قها','value_EN' => 'Qaha'],
            ['id' =>28 ,'gov_id' => 12,'value_AR' => 'العبور', 'value_EN' =>'Obour'],
            ['id' =>29 ,'gov_id' => 12,'value_AR' => 'الخصوص','value_EN' => 'Khosous'],
            ['id' =>30 ,'gov_id' => 12,'value_AR' => 'شبين القناطر','value_EN' => 'Shibin Al Qanater'],
            ['id' =>31 ,'gov_id' => 6, 'value_AR' =>'دمنهور', 'value_EN' =>'Damanhour'],
            ['id' =>32 ,'gov_id' => 6, 'value_AR' =>'كفر الدوار','value_EN' => 'Kafr El Dawar'],
            ['id' =>33 ,'gov_id' => 6, 'value_AR' =>'رشيد', 'value_EN' =>'Rashid'],
            ['id' =>34 ,'gov_id' => 6, 'value_AR' =>'إدكو', 'value_EN' =>'Edco'],
            ['id' =>35 ,'gov_id' => 6, 'value_AR' =>'أبو المطامير','value_EN' => 'Abu al-Matamir'],
            ['id' =>36 ,'gov_id' => 6, 'value_AR' =>'أبو حمص', 'value_EN' =>'Abu Homs'],
            ['id' =>37 ,'gov_id' => 6, 'value_AR' =>'الدلنجات', 'value_EN' =>'Delengat'],
            ['id' =>38 ,'gov_id' => 6, 'value_AR' =>'المحمودية','value_EN' => 'Mahmoudiyah'],
            ['id' =>39 ,'gov_id' => 6, 'value_AR' =>'الرحمانية','value_EN' => 'Rahmaniyah'],
            ['id' =>40 ,'gov_id' => 6, 'value_AR' =>'إيتاي البارود','value_EN' => 'Itai Baroud'],
            ['id' =>41 ,'gov_id' => 6, 'value_AR' =>'حوش عيسى','value_EN' => 'Housh Eissa'],
            ['id' =>42 ,'gov_id' => 6, 'value_AR' =>'شبراخيت','value_EN' => 'Shubrakhit'],
            ['id' =>43 ,'gov_id' => 6, 'value_AR' =>'كوم حمادة','value_EN' => 'Kom Hamada'],
            ['id' =>44 ,'gov_id' => 6, 'value_AR' =>'بدر','value_EN' => 'Badr'],
            ['id' =>45 ,'gov_id' => 6, 'value_AR' =>'وادي النطرون','value_EN' => 'Wadi Natrun'],
            ['id' =>46 ,'gov_id' => 6, 'value_AR' =>'النوبارية الجديدة', 'value_EN' =>'New Nubaria'],
            ['id' =>47 ,'gov_id' => 23,'value_AR' => 'مرسى مطروح','value_EN' => 'Marsa Matrouh'],
            ['id' =>48 ,'gov_id' => 23,'value_AR' => 'الحمام', 'value_EN' =>'El Hamam'],
            ['id' =>49 ,'gov_id' => 23,'value_AR' => 'العلمين', 'value_EN' =>'Alamein'],
            ['id' =>50 ,'gov_id' => 23,'value_AR' => 'الضبعة', 'value_EN' =>'Dabaa'],
            ['id' =>51 ,'gov_id' => 23,'value_AR' => 'النجيلة', 'value_EN' =>'Al-Nagila'],
            ['id' =>52 ,'gov_id' => 23,'value_AR' => 'سيدي براني', 'value_EN' =>'Sidi Brani'],
            ['id' =>53 ,'gov_id' => 23,'value_AR' => 'السلوم', 'value_EN' =>'Salloum'],
            ['id' =>54 ,'gov_id' => 23,'value_AR' => 'سيوة', 'value_EN' =>'Siwa'],
            ['id' =>55 ,'gov_id' => 19,'value_AR' => 'دمياط', 'value_EN' =>'Damietta'],
            ['id' =>56 ,'gov_id' => 19,'value_AR' => 'دمياط الجديدة','value_EN' => 'New Damietta'],
            ['id' =>57 ,'gov_id' => 19,'value_AR' => 'رأس البر', 'value_EN' =>'Ras El Bar'],
            ['id' =>58 ,'gov_id' => 19,'value_AR' => 'فارسكور', 'value_EN' =>'Faraskour'],
            ['id' =>59 ,'gov_id' => 19,'value_AR' => 'الزرقا', 'value_EN' =>'Zarqa'],
            ['id' =>60 ,'gov_id' => 19,'value_AR' => 'السرو','value_EN' => 'alsaru'],
            ['id' =>61 ,'gov_id' => 19,'value_AR' => 'الروضة', 'value_EN' =>'alruwda'],
            ['id' =>62 ,'gov_id' => 19,'value_AR' => 'كفر البطيخ','value_EN' => 'Kafr El-Batikh'],
            ['id' =>63 ,'gov_id' => 19,'value_AR' => 'عزبة البرج', 'value_EN' =>'Azbet Al Burg'],
            ['id' =>64 ,'gov_id' => 19,'value_AR' => 'ميت أبو غالب', 'value_EN' =>'Meet Abou Ghalib'],
            ['id' =>65 ,'gov_id' => 19,'value_AR' => 'كفر سعد', 'value_EN' =>'Kafr Saad'],
            ['id' =>66 ,'gov_id' => 4, 'value_AR' =>'المنصورة', 'value_EN' =>'Mansoura'],
            ['id' =>67 ,'gov_id' => 4, 'value_AR' =>'طلخا', 'value_EN' =>'Talkha'],
            ['id' =>68 ,'gov_id' => 4, 'value_AR' =>'ميت غمر', 'value_EN' =>'Mitt Ghamr'],
            ['id' =>69 ,'gov_id' => 4, 'value_AR' =>'دكرنس', 'value_EN' =>'Dekernes'],
            ['id' =>70 ,'gov_id' => 4, 'value_AR' =>'أجا','value_EN' => 'Aga'],
            ['id' =>71 ,'gov_id' => 4, 'value_AR' =>'منية النصر', 'value_EN' =>'Menia El Nasr'],
            ['id' =>72 ,'gov_id' => 4, 'value_AR' =>'السنبلاوين', 'value_EN' =>'Sinbillawin'],
            ['id' =>73 ,'gov_id' => 4, 'value_AR' =>'الكردي', 'value_EN' =>'El Kurdi'],
            ['id' =>74 ,'gov_id' => 4, 'value_AR' =>'بني عبيد', 'value_EN' =>'Bani Ubaid'],
            ['id' =>75 ,'gov_id' => 4, 'value_AR' =>'المنزلة', 'value_EN' =>'Al Manzala'],
            ['id' =>76 ,'gov_id' => 4, 'value_AR' =>'تمي الأمديد', 'value_EN' =>'tami al\'amdid'],
            ['id' =>77 ,'gov_id' => 4, 'value_AR' =>'الجمالية','value_EN' => 'aljamalia'],
            ['id' =>78 ,'gov_id' => 4, 'value_AR' =>'شربين', 'value_EN' =>'Sherbin'],
            ['id' =>79 ,'gov_id' => 4, 'value_AR' =>'المطرية', 'value_EN' =>'Mataria'],
            ['id' =>80 ,'gov_id' => 4, 'value_AR' =>'بلقاس', 'value_EN' =>'Belqas'],
            ['id' =>81 ,'gov_id' => 4, 'value_AR' =>'ميت سلسيل', 'value_EN' =>'Meet Salsil'],
            ['id' =>82 ,'gov_id' => 4, 'value_AR' =>'جمصة', 'value_EN' =>'Gamasa'],
            ['id' =>83 ,'gov_id' => 4, 'value_AR' =>'محلة دمنة', 'value_EN' =>'Mahalat Damana'],
            ['id' =>84 ,'gov_id' => 4, 'value_AR' =>'نبروه', 'value_EN' =>'Nabroh'],
            ['id' =>85 ,'gov_id' => 22,'value_AR' => 'كفر الشيخ', 'value_EN' =>'Kafr El Sheikh'],
            ['id' =>86 ,'gov_id' => 22,'value_AR' => 'دسوق', 'value_EN' =>'Desouq'],
            ['id' =>87 ,'gov_id' => 22,'value_AR' => 'فوه', 'value_EN' =>'Fooh'],
            ['id' =>88 ,'gov_id' => 22,'value_AR' => 'مطوبس', 'value_EN' =>'Metobas'],
            ['id' =>89 ,'gov_id' => 22,'value_AR' => 'برج البرلس', 'value_EN' =>'Burg Al Burullus'],
            ['id' =>90 ,'gov_id' => 22,'value_AR' => 'بلطيم', 'value_EN' =>'Baltim'],
            ['id' =>91 ,'gov_id' => 22,'value_AR' => 'مصيف بلطيم','value_EN' => 'Masief Baltim'],
            ['id' =>92 ,'gov_id' => 22,'value_AR' => 'الحامول', 'value_EN' =>'Hamol'],
            ['id' =>93 ,'gov_id' => 22,'value_AR' => 'بيلا', 'value_EN' =>'Bella'],
            ['id' =>94 ,'gov_id' => 22,'value_AR' => 'الرياض','value_EN' => 'Riyadh'],
            ['id' =>95 ,'gov_id' => 22,'value_AR' => 'سيدي سالم', 'value_EN' =>'Sidi Salm'],
            ['id' =>96 ,'gov_id' => 22,'value_AR' => 'قلين', 'value_EN' =>'Qellen'],
            ['id' =>97 ,'gov_id' => 22,'value_AR' => 'سيدي غازي','value_EN' => 'Sidi Ghazi'],
            ['id' =>98 ,'gov_id' => 8, 'value_AR' =>'طنطا', 'value_EN' =>'Tanta'],
            ['id' =>99 ,'gov_id' => 8, 'value_AR' =>'المحلة الكبرى', 'value_EN' =>'Al Mahalla Al Kobra'],
            ['id' =>100,'gov_id' => 8, 'value_AR' =>'كفر الزيات', 'value_EN' =>'Kafr El Zayat'],
            ['id' =>101,'gov_id' => 8, 'value_AR' =>'زفتى', 'value_EN' =>'Zefta'],
            ['id' =>102,'gov_id' => 8, 'value_AR' =>'السنطة', 'value_EN' =>'El Santa'],
            ['id' =>103,'gov_id' => 8, 'value_AR' =>'قطور', 'value_EN' =>'Qutour'],
            ['id' =>104,'gov_id' => 8, 'value_AR' =>'بسيون', 'value_EN' =>'Basion'],
            ['id' =>105,'gov_id' => 8, 'value_AR' =>'سمنود', 'value_EN' =>'Samannoud'],
            ['id' =>106,'gov_id' => 10,'value_AR' => 'شبين الكوم','value_EN' => 'Shbeen El Koom'],
            ['id' =>107,'gov_id' => 10,'value_AR' => 'مدينة السادات', 'value_EN' =>'Sadat City'],
            ['id' =>108,'gov_id' => 10,'value_AR' => 'منوف', 'value_EN' =>'Menouf'],
            ['id' =>109,'gov_id' => 10,'value_AR' => 'سرس الليان','value_EN' => 'Sars El-Layan'],
            ['id' =>110,'gov_id' => 10,'value_AR' => 'أشمون', 'value_EN' =>'Ashmon'],
            ['id' =>111,'gov_id' => 10,'value_AR' => 'الباجور', 'value_EN' =>'Al Bagor'],
            ['id' =>112,'gov_id' => 10,'value_AR' => 'قويسنا', 'value_EN' =>'Quesna'],
            ['id' =>113,'gov_id' => 10,'value_AR' => 'بركة السبع', 'value_EN' =>'Berkat El Saba'],
            ['id' =>114,'gov_id' => 10,'value_AR' => 'تلا', 'value_EN' =>'Tala'],
            ['id' =>115,'gov_id' => 10,'value_AR' => 'الشهداء', 'value_EN' =>'Al Shohada'],
            ['id' =>116,'gov_id' => 20,'value_AR' => 'الزقازيق', 'value_EN' =>'Zagazig'],
            ['id' =>117,'gov_id' => 20,'value_AR' => 'العاشر من رمضان', 'value_EN' =>'Al Ashr Men Ramadan'],
            ['id' =>118,'gov_id' => 20,'value_AR' => 'منيا القمح', 'value_EN' =>'Minya Al Qamh'],
            ['id' =>119,'gov_id' => 20,'value_AR' => 'بلبيس', 'value_EN' =>'Belbeis'],
            ['id' =>120,'gov_id' => 20,'value_AR' => 'مشتول السوق', 'value_EN' =>'Mashtoul El Souq'],
            ['id' =>121,'gov_id' => 20,'value_AR' => 'القنايات','value_EN' => 'Qenaiat'],
            ['id' =>122,'gov_id' => 20,'value_AR' => 'أبو حماد', 'value_EN' =>'Abu Hammad'],
            ['id' =>123,'gov_id' => 20,'value_AR' => 'القرين', 'value_EN' =>'El Qurain'],
            ['id' =>124,'gov_id' => 20,'value_AR' => 'ههيا', 'value_EN' =>'Hehia'],
            ['id' =>125,'gov_id' => 20,'value_AR' => 'أبو كبير', 'value_EN' =>'Abu Kabir'],
            ['id' =>126,'gov_id' => 20,'value_AR' => 'فاقوس', 'value_EN' =>'Faccus'],
            ['id' =>127,'gov_id' => 20,'value_AR' => 'الصالحية الجديدة', 'value_EN' =>'El Salihia El Gedida'],
            ['id' =>128,'gov_id' => 20,'value_AR' => 'الإبراهيمية', 'value_EN' =>'Al Ibrahimiyah'],
            ['id' =>129,'gov_id' => 20,'value_AR' => 'ديرب نجم', 'value_EN' =>'Deirb Negm'],
            ['id' =>130,'gov_id' => 20,'value_AR' => 'كفر صقر', 'value_EN' =>'Kafr Saqr'],
            ['id' =>131,'gov_id' => 20,'value_AR' => 'أولاد صقر', 'value_EN' =>'Awlad Saqr'],
            ['id' =>132,'gov_id' => 20,'value_AR' => 'الحسينية', 'value_EN' =>'Husseiniya'],
            ['id' =>133,'gov_id' => 20,'value_AR' => 'صان الحجر القبلية', 'value_EN' =>'san alhajar alqablia'],
            ['id' =>134,'gov_id' => 20,'value_AR' => 'منشأة أبو عمر', 'value_EN' =>'Manshayat Abu Omar'],
            ['id' =>135,'gov_id' => 18,'value_AR' => 'بورسعيد', 'value_EN' =>'PorSaid'],
            ['id' =>136,'gov_id' => 18,'value_AR' => 'بورفؤاد', 'value_EN' =>'PorFouad'],
            ['id' =>137,'gov_id' => 9, 'value_AR' =>'الإسماعيلية', 'value_EN' =>'Ismailia'],
            ['id' =>138,'gov_id' => 9, 'value_AR' =>'فايد', 'value_EN' =>'Fayed'],
            ['id' =>139,'gov_id' => 9, 'value_AR' =>'القنطرة شرق', 'value_EN' =>'Qantara Sharq'],
            ['id' =>140,'gov_id' => 9, 'value_AR' =>'القنطرة غرب', 'value_EN' =>'Qantara Gharb'],
            ['id' =>141,'gov_id' => 9, 'value_AR' =>'التل الكبير', 'value_EN' =>'El Tal El Kabier'],
            ['id' =>142,'gov_id' => 9, 'value_AR' =>'أبو صوير', 'value_EN' =>'Abu Sawir'],
            ['id' =>143,'gov_id' => 9, 'value_AR' =>'القصاصين الجديدة', 'value_EN' =>'Kasasien El Gedida'],
            ['id' =>144,'gov_id' => 14,'value_AR' => 'السويس', 'value_EN' =>'Suez'],
            ['id' =>145,'gov_id' => 26,'value_AR' => 'العريش', 'value_EN' =>'Arish'],
            ['id' =>146,'gov_id' => 26,'value_AR' => 'الشيخ زويد', 'value_EN' =>'Sheikh Zowaid'],
            ['id' =>147,'gov_id' => 26,'value_AR' => 'نخل', 'value_EN' =>'Nakhl'],
            ['id' =>148,'gov_id' => 26,'value_AR' => 'رفح', 'value_EN' =>'Rafah'],
            ['id' =>149,'gov_id' => 26,'value_AR' => 'بئر العبد', 'value_EN' =>'Bir al-Abed'],
            ['id' =>150,'gov_id' => 26,'value_AR' => 'الحسنة', 'value_EN' =>'Al Hasana'],
            ['id' =>151,'gov_id' => 21,'value_AR' => 'الطور', 'value_EN' =>'Al Toor'],
            ['id' =>152,'gov_id' => 21,'value_AR' => 'شرم الشيخ', 'value_EN' =>'Sharm El-Shaikh'],
            ['id' =>153,'gov_id' => 21,'value_AR' => 'دهب', 'value_EN' =>'Dahab'],
            ['id' =>154,'gov_id' => 21,'value_AR' => 'نويبع', 'value_EN' =>'Nuweiba'],
            ['id' =>155,'gov_id' => 21,'value_AR' => 'طابا', 'value_EN' =>'Taba'],
            ['id' =>156,'gov_id' => 21,'value_AR' => 'سانت كاترين', 'value_EN' =>'Saint Catherine'],
            ['id' =>157,'gov_id' => 21,'value_AR' => 'أبو رديس', 'value_EN' =>'Abu Redis'],
            ['id' =>158,'gov_id' => 21,'value_AR' => 'أبو زنيمة', 'value_EN' =>'Abu Zenaima'],
            ['id' =>159,'gov_id' => 21,'value_AR' => 'رأس سدر', 'value_EN' =>'Ras Sidr'],
            ['id' =>160,'gov_id' => 17,'value_AR' => 'بني سويف', 'value_EN' =>'Bani Sweif'],
            ['id' =>161,'gov_id' => 17,'value_AR' => 'بني سويف الجديدة', 'value_EN' =>'Beni Suef El Gedida'],
            ['id' =>162,'gov_id' => 17,'value_AR' => 'الواسطى', 'value_EN' =>'Al Wasta'],
            ['id' =>163,'gov_id' => 17,'value_AR' => 'ناصر', 'value_EN' =>'Naser'],
            ['id' =>164,'gov_id' => 17,'value_AR' => 'إهناسيا', 'value_EN' =>'Ehnasia'],
            ['id' =>165,'gov_id' => 17,'value_AR' => 'ببا', 'value_EN' =>'beba'],
            ['id' =>166,'gov_id' => 17,'value_AR' => 'الفشن', 'value_EN' =>'Fashn'],
            ['id' =>167,'gov_id' => 17,'value_AR' => 'سمسطا', 'value_EN' =>'Somasta'],
            ['id' =>168,'gov_id' => 7, 'value_AR' =>'الفيوم', 'value_EN' =>'Fayoum'],
            ['id' =>169,'gov_id' => 7, 'value_AR' =>'الفيوم الجديدة', 'value_EN' =>'Fayoum El Gedida'],
            ['id' =>170,'gov_id' => 7, 'value_AR' =>'طامية','value_EN' => 'Tamiya'],
            ['id' =>171,'gov_id' => 7, 'value_AR' =>'سنورس','value_EN' => 'Snores'],
            ['id' =>172,'gov_id' => 7, 'value_AR' =>'إطسا', 'value_EN' =>'Etsa'],
            ['id' =>173,'gov_id' => 7, 'value_AR' =>'إبشواي', 'value_EN' =>'Epschway'],
            ['id' =>174,'gov_id' => 7, 'value_AR' =>'يوسف الصديق', 'value_EN' =>'Yusuf El Sediaq'],
            ['id' =>175,'gov_id' => 11,'value_AR' => 'المنيا', 'value_EN' =>'Minya'],
            ['id' =>176,'gov_id' => 11,'value_AR' => 'المنيا الجديدة', 'value_EN' =>'Minya El Gedida'],
            ['id' =>177,'gov_id' => 11,'value_AR' => 'العدوة', 'value_EN' =>'El Adwa'],
            ['id' =>178,'gov_id' => 11,'value_AR' => 'مغاغة', 'value_EN' =>'Magagha'],
            ['id' =>179,'gov_id' => 11,'value_AR' => 'بني مزار', 'value_EN' =>'Bani Mazar'],
            ['id' =>180,'gov_id' => 11,'value_AR' => 'مطاي', 'value_EN' =>'Mattay'],
            ['id' =>181,'gov_id' => 11,'value_AR' => 'سمالوط', 'value_EN' =>'Samalut'],
            ['id' =>182,'gov_id' => 11,'value_AR' => 'المدينة الفكرية', 'value_EN' =>'Madinat El Fekria'],
            ['id' =>183,'gov_id' => 11,'value_AR' => 'ملوي', 'value_EN' =>'Meloy'],
            ['id' =>184,'gov_id' => 11,'value_AR' => 'دير مواس', 'value_EN' =>'Deir Mawas'],
            ['id' =>185,'gov_id' => 16,'value_AR' => 'أسيوط', 'value_EN' =>'Assiut'],
            ['id' =>186,'gov_id' => 16,'value_AR' => 'أسيوط الجديدة', 'value_EN' =>'Assiut El Gedida'],
            ['id' =>187,'gov_id' => 16,'value_AR' => 'ديروط', 'value_EN' =>'Dayrout'],
            ['id' =>188,'gov_id' => 16,'value_AR' => 'منفلوط', 'value_EN' =>'Manfalut'],
            ['id' =>189,'gov_id' => 16,'value_AR' => 'القوصية', 'value_EN' =>'Qusiya'],
            ['id' =>190,'gov_id' => 16,'value_AR' => 'أبنوب', 'value_EN' =>'Abnoub'],
            ['id' =>191,'gov_id' => 16,'value_AR' => 'أبو تيج','value_EN' => 'Abu Tig'],
            ['id' =>192,'gov_id' => 16,'value_AR' => 'الغنايم', 'value_EN' =>'El Ghanaim'],
            ['id' =>193,'gov_id' => 16,'value_AR' => 'ساحل سليم', 'value_EN' =>'Sahel Selim'],
            ['id' =>194,'gov_id' => 16,'value_AR' => 'البداري', 'value_EN' =>'El Badari'],
            ['id' =>195,'gov_id' => 16,'value_AR' => 'صدفا', 'value_EN' =>'Sidfa'],
            ['id' =>196,'gov_id' => 13,'value_AR' => 'الخارجة', 'value_EN' =>'El Kharga'],
            ['id' =>197,'gov_id' => 13,'value_AR' => 'باريس', 'value_EN' =>'Paris'],
            ['id' =>198,'gov_id' => 13,'value_AR' => 'موط', 'value_EN' =>'Mout'],
            ['id' =>199,'gov_id' => 13,'value_AR' => 'الفرافرة', 'value_EN' =>'Farafra'],
            ['id' =>200,'gov_id' => 13,'value_AR' => 'بلاط', 'value_EN' =>'Balat'],
            ['id' =>201,'gov_id' => 5, 'value_AR' =>'الغردقة', 'value_EN' =>'Hurghada'],
            ['id' =>202,'gov_id' => 5, 'value_AR' =>'رأس غارب', 'value_EN' =>'Ras Ghareb'],
            ['id' =>203,'gov_id' => 5, 'value_AR' =>'سفاجا', 'value_EN' =>'Safaga'],
            ['id' =>204,'gov_id' => 5, 'value_AR' =>'القصير', 'value_EN' =>'El Qusiar'],
            ['id' =>205,'gov_id' => 5, 'value_AR' =>'مرسى علم', 'value_EN' =>'Marsa Alam'],
            ['id' =>206,'gov_id' => 5, 'value_AR' =>'الشلاتين', 'value_EN' =>'Shalatin'],
            ['id' =>207,'gov_id' => 5, 'value_AR' =>'حلايب', 'value_EN' =>'Halaib'],
            ['id' =>208,'gov_id' => 27,'value_AR' => 'سوهاج', 'value_EN' =>'Sohag'],
            ['id' =>209,'gov_id' => 27,'value_AR' => 'سوهاج الجديدة', 'value_EN' =>'Sohag El Gedida'],
            ['id' =>210,'gov_id' => 27,'value_AR' => 'أخميم', 'value_EN' =>'Akhmeem'],
            ['id' =>211,'gov_id' => 27,'value_AR' => 'أخميم الجديدة', 'value_EN' =>'Akhmim El Gedida'],
            ['id' =>212,'gov_id' => 27,'value_AR' => 'البلينا', 'value_EN' =>'Albalina'],
            ['id' =>213,'gov_id' => 27,'value_AR' => 'المراغة', 'value_EN' =>'El Maragha'],
            ['id' =>214,'gov_id' => 27,'value_AR' => 'المنشأة', 'value_EN' =>'almunsha\'a'],
            ['id' =>215,'gov_id' => 27,'value_AR' => 'دار السلام', 'value_EN' =>'Dar AISalaam'],
            ['id' =>216,'gov_id' => 27,'value_AR' => 'جرجا','value_EN' => 'Gerga'],
            ['id' =>217,'gov_id' => 27,'value_AR' => 'جهينة الغربية', 'value_EN' =>'Jahina Al Gharbia'],
            ['id' =>218,'gov_id' => 27,'value_AR' => 'ساقلته', 'value_EN' =>'Saqilatuh'],
            ['id' =>219,'gov_id' => 27,'value_AR' => 'طما', 'value_EN' =>'Tama'],
            ['id' =>220,'gov_id' => 27,'value_AR' => 'طهطا','value_EN' => 'Tahta'],
            ['id' =>221,'gov_id' => 25,'value_AR' => 'قنا', 'value_EN' =>'Qena'],
            ['id' =>222,'gov_id' => 25,'value_AR' => 'قنا الجديدة', 'value_EN' =>'New Qena'],
            ['id' =>223,'gov_id' => 25,'value_AR' => 'أبو تشت', 'value_EN' =>'Abu Tesht'],
            ['id' =>224,'gov_id' => 25,'value_AR' => 'نجع حمادي', 'value_EN' =>'Nag Hammadi'],
            ['id' =>225,'gov_id' => 25,'value_AR' => 'دشنا', 'value_EN' =>'Deshna'],
            ['id' =>226,'gov_id' => 25,'value_AR' => 'الوقف', 'value_EN' =>'Alwaqf'],
            ['id' =>227,'gov_id' => 25,'value_AR' => 'قفط', 'value_EN' =>'Qaft'],
            ['id' =>228,'gov_id' => 25,'value_AR' => 'نقادة', 'value_EN' =>'Naqada'],
            ['id' =>229,'gov_id' => 25,'value_AR' => 'فرشوط','value_EN' => 'Farshout'],
            ['id' =>230,'gov_id' => 25,'value_AR' => 'قوص', 'value_EN' =>'Quos'],
            ['id' =>231,'gov_id' => 24,'value_AR' => 'الأقصر', 'value_EN' =>'Luxor'],
            ['id' =>232,'gov_id' => 24,'value_AR' => 'الأقصر الجديدة','value_EN' => 'New Luxor'],
            ['id' =>233,'gov_id' => 24,'value_AR' => 'إسنا', 'value_EN' =>'Esna'],
            ['id' =>234,'gov_id' => 24,'value_AR' => 'طيبة الجديدة', 'value_EN' =>'New Tiba'],
            ['id' =>235,'gov_id' => 24,'value_AR' => 'الزينية', 'value_EN' =>'Al ziynia'],
            ['id' =>236,'gov_id' => 24,'value_AR' => 'البياضية','value_EN' => 'Al Bayadieh'],
            ['id' =>237,'gov_id' => 24,'value_AR' => 'القرنة','value_EN' => 'Al Qarna'],
            ['id' =>238,'gov_id' => 24,'value_AR' => 'أرمنت', 'value_EN' =>'Armant'],
            ['id' =>239,'gov_id' => 24,'value_AR' => 'الطود', 'value_EN' =>'Al Tud'],
            ['id' =>240,'gov_id' => 15,'value_AR' => 'أسوان', 'value_EN' =>'Aswan'],
            ['id' =>241,'gov_id' => 15,'value_AR' => 'أسوان الجديدة', 'value_EN' =>'Aswan El Gedida'],
            ['id' =>242,'gov_id' => 15,'value_AR' => 'دراو', 'value_EN' =>'Drau'],
            ['id' =>243,'gov_id' => 15,'value_AR' => 'كوم أمبو', 'value_EN' =>'Kom Ombo'],
            ['id' =>244,'gov_id' => 15,'value_AR' => 'نصر النوبة', 'value_EN' =>'Nasr Al Nuba'],
            ['id' =>245,'gov_id' => 15,'value_AR' => 'كلابشة', 'value_EN' =>'Kalabsha'],
            ['id' =>246,'gov_id' => 15,'value_AR' => 'إدفو', 'value_EN' =>'Edfu'],
            ['id' =>247,'gov_id' => 15,'value_AR' => 'الرديسية', 'value_EN' =>'Al-Radisiyah'],
            ['id' =>248,'gov_id' => 15,'value_AR' => 'البصيلية', 'value_EN' =>'Al Basilia'],
            ['id' =>249,'gov_id' => 15,'value_AR' => 'السباعية', 'value_EN' =>'Al Sibaeia'],
            ['id' =>250,'gov_id' => 15,'value_AR' => 'ابوسمبل السياحية', 'value_EN' =>'Abo Simbl Al Siyahia']
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
